import { ProductStockStatus } from "@prisma/client";

export const productsData = [
  {
    name: "Lait",
    slug: "lait",
    description: "Lait frais pour la consommation quotidienne.",
    price: 1800,
    quantity: 12,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/lait.jpg",
    isActive: true,
    isFeatured: true,
    categorySlug: "produits-laitiers",
  },
  {
    name: "Œufs",
    slug: "oeufs",
    description: "Œufs frais sélectionnés.",
    price: 2500,
    quantity: 10,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/oeufs.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "produits-laitiers",
  },
  {
    name: "Pain",
    slug: "pain",
    description: "Pain frais du jour.",
    price: 500,
    quantity: 15,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/pain.jpg",
    isActive: true,
    isFeatured: true,
    categorySlug: "boulangerie",
  },
  {
    name: "Riz",
    slug: "riz",
    description: "Riz de qualité pour toute la famille.",
    price: 4500,
    quantity: 20,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/riz.jpg",
    isActive: true,
    isFeatured: true,
    categorySlug: "produits-secs",
  },
  {
    name: "Pâtes",
    slug: "pates",
    description: "Pâtes alimentaires pratiques et rapides.",
    price: 1200,
    quantity: 14,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/pates.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "produits-secs",
  },
  {
    name: "Poulet",
    slug: "poulet",
    description: "Poulet frais prêt à cuisiner.",
    price: 6500,
    quantity: 8,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/poulet.jpg",
    isActive: true,
    isFeatured: true,
    categorySlug: "viande-poisson",
  },
  {
    name: "Pommes",
    slug: "pommes",
    description: "Pommes fraîches sélectionnées.",
    price: 2200,
    quantity: 9,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/pommes.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "legumes-fruits",
  },
  {
    name: "Eau minérale",
    slug: "eau-minerale",
    description: "Eau minérale en bouteille.",
    price: 800,
    quantity: 25,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/eau-minerale.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "boissons",
  },
  {
    name: "Jus d’orange",
    slug: "jus-orange",
    description: "Jus d’orange rafraîchissant.",
    price: 1500,
    quantity: 12,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/jus-orange.jpg",
    isActive: true,
    isFeatured: true,
    categorySlug: "boissons",
  },
  {
    name: "Soda",
    slug: "soda",
    description: "Boisson gazeuse fraîche.",
    price: 1000,
    quantity: 18,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/soda.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "boissons",
  },
  {
    name: "Pizza surgelée",
    slug: "pizza-surgelee",
    description: "Pizza surgelée prête à cuire.",
    price: 4000,
    quantity: 6,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/pizza-surgelee.jpg",
    isActive: true,
    isFeatured: true,
    categorySlug: "produits-surgeles",
  },
  {
    name: "Frites surgelées",
    slug: "frites-surgelees",
    description: "Frites surgelées croustillantes.",
    price: 2500,
    quantity: 7,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/frites-surgelees.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "produits-surgeles",
  },
  {
    name: "Parfum",
    slug: "parfum",
    description: "Parfum élégant longue tenue.",
    price: 12000,
    quantity: 5,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/parfum.jpg",
    isActive: true,
    isFeatured: true,
    categorySlug: "hygiene-beaute",
  },
  {
    name: "Déodorant",
    slug: "deodorant",
    description: "Déodorant fraîcheur longue durée.",
    price: 2500,
    quantity: 11,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/deodorant.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "hygiene-beaute",
  },
  {
    name: "Shampooing",
    slug: "shampooing",
    description: "Shampooing soin quotidien.",
    price: 3500,
    quantity: 10,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/shampooing.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "hygiene-beaute",
  },
  {
    name: "Gel douche",
    slug: "gel-douche",
    description: "Gel douche parfumé.",
    price: 3000,
    quantity: 10,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/gel-douche.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "hygiene-beaute",
  },
  {
    name: "Dentifrice",
    slug: "dentifrice",
    description: "Dentifrice pour hygiène quotidienne.",
    price: 1500,
    quantity: 16,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/dentifrice.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "hygiene-beaute",
  },
  {
    name: "Fond de teint",
    slug: "fond-de-teint",
    description: "Fond de teint couvrance naturelle.",
    price: 5500,
    quantity: 5,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/fond-de-teint.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "hygiene-beaute",
  },
  {
    name: "Mascara",
    slug: "mascara",
    description: "Mascara volume intense.",
    price: 4000,
    quantity: 8,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/mascara.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "hygiene-beaute",
  },
  {
    name: "Rouge à lèvres",
    slug: "rouge-a-levres",
    description: "Rouge à lèvres longue tenue.",
    price: 3500,
    quantity: 7,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/rouge-a-levres.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "hygiene-beaute",
  },
  {
    name: "Crème hydratante",
    slug: "creme-hydratante",
    description: "Crème hydratante visage et corps.",
    price: 4500,
    quantity: 9,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/creme-hydratante.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "hygiene-beaute",
  },
  {
    name: "Démaquillant",
    slug: "demaquillant",
    description: "Démaquillant douceur.",
    price: 3800,
    quantity: 6,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/demaquillant.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "hygiene-beaute",
  },
  {
    name: "Kinder Bueno",
    slug: "kinder-bueno",
    description: "Barre chocolatée Kinder Bueno.",
    price: 1200,
    quantity: 20,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/kinder-bueno.jpg",
    isActive: true,
    isFeatured: true,
    categorySlug: "produits-secs",
  },
  {
    name: "Kinder Surprise",
    slug: "kinder-surprise",
    description: "Œuf Kinder Surprise.",
    price: 1000,
    quantity: 18,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/kinder-surprise.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "produits-secs",
  },
  {
    name: "Kinder Chocolate",
    slug: "kinder-chocolate",
    description: "Tablette Kinder Chocolate.",
    price: 1500,
    quantity: 16,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/kinder-chocolate.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "produits-secs",
  },
  {
    name: "Kinder Maxi",
    slug: "kinder-maxi",
    description: "Kinder Maxi chocolat au lait.",
    price: 1300,
    quantity: 15,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/kinder-maxi.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "produits-secs",
  },
  {
    name: "Kinder Schoko-Bons",
    slug: "kinder-schoko-bons",
    description: "Kinder Schoko-Bons croustillants.",
    price: 1800,
    quantity: 12,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/kinder-schoko-bons.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "produits-secs",
  },
  {
    name: "Kinder Country",
    slug: "kinder-country",
    description: "Barre Kinder Country.",
    price: 1400,
    quantity: 14,
    stockStatus: ProductStockStatus.IN_STOCK,
    imageUrl: "/products/kinder-country.jpg",
    isActive: true,
    isFeatured: false,
    categorySlug: "produits-secs",
  },
];